- src/mixins/component.js
> [#31] Added DruxtWrapper to DruxtComponentMixin.

- src/mixins/__tests__/component.test.js
- src/mixins/component.js
> [#30] Added unique filter to component options.

- src/__tests__/class.test.js
- src/class.js
- src/mixins/__tests__/component.test.js
- src/mixins/component.js
> [#34] Fixed component options creation.

- docs/guide/getting-started.md
- src/components/Druxt.vue
- src/components/__tests__/Druxt.test.js
- src/components/__tests__/__snapshots__/Druxt.test.js.snap
- src/mixins/component.js
> [#36] Added Inner prop.

- README.md
- docs/README.md
- docs/guide/README.md
- examples/custom-module/components/druxt/CustomModule.vue
- examples/custom-module/components/druxt/custom-module/Wrapper.vue
- package-lock.json
- package.json
- src/class.js
- src/components/DruxtModule.vue
- src/components/__tests__/DruxtModule.test.js
- src/components/__tests__/__snapshots__/DruxtModule.test.js.snap
- src/index.js
- src/mixins/component.js
Added DruxtModule component
Deprecated DruxtClass and DruxtComponentMixin
> [#54] Added DruxtModule component.

- package-lock.json
- package.json
- src/stores/__tests__/druxt.test.js
- src/stores/druxt.js
Fixed additional issue in the getResource action.
> [#73] Fixed issue with queryobject in getResource action.

- src/components/DruxtModule.vue
+ Add condition to emit Model on Watch if component is DruxtWrapper.
+ Added emit to Input event.
> [#80] fix: emit on input or watch if DruxtWrapper.

- src/components/DruxtModule.vue
+ Prevent `data-fetch-key` from being passed through to render components.
> [#83] Fixed bug with fetchKey and attrs passthru.

- .gitignore
- .gitpod.yml
- .vscode/settings.json
https://open-vsx.org/extension/Gruntfuggly/todo-tree
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/88"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Added and configured TODO Tree VS Code extension

- CODE_OF_CONDUCT.md
Added Contributor Covenant: https://www.contributor-covenant.org
Closes #143
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/144"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs(#143): add Code of Conduct

- .editorconfig
- .gitpod.yml
- jsconfig.json
Added .editorconfig
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/151"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> chore(#140): add .editorconfig

- packages/blocks/README.md
- packages/blocks/package.json
- packages/breadcrumb/README.md
- packages/breadcrumb/package.json
- packages/docgen/README.md
- packages/docgen/package.json
- packages/druxt/package.json
- packages/entity/README.md
- packages/entity/package.json
- packages/menu/README.md
- packages/menu/package.json
- packages/router/README.md
- packages/router/package.json
- packages/schema/README.md
- packages/schema/package.json
- packages/site/README.md
- packages/site/package.json
- packages/test-utils/package.json
- packages/views/README.md
- packages/views/package.json
+ Update package descriptions
+ Resolves #164
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/165"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs(#164): update package descriptions

- packages/blocks/src/components/DruxtBlock.vue
- packages/blocks/src/components/DruxtBlockRegion.vue
- packages/breadcrumb/src/components/DruxtBreadcrumb.vue
- packages/druxt/src/components/Druxt.vue
- packages/druxt/src/components/DruxtModule.vue
- packages/druxt/src/components/DruxtWrapper.vue
- packages/entity/src/components/DruxtEntity.vue
- packages/entity/src/components/DruxtEntityForm.vue
- packages/entity/src/components/DruxtEntityFormButtons.vue
- packages/entity/src/components/DruxtField.vue
- packages/menu/src/components/DruxtMenu.vue
- packages/menu/src/components/DruxtMenuItem.vue
- packages/router/src/components/DruxtRouter.vue
- packages/site/src/components/DruxtSite.vue
- packages/views/src/components/DruxtView.vue
- packages/views/src/components/DruxtViewsFilter.vue
- packages/views/src/components/DruxtViewsFilters.vue
- packages/views/src/components/DruxtViewsPager.vue
- packages/views/src/components/DruxtViewsSorts.vue
+ Updated component descriptions for documentation site.
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/171"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs(#169): update component descriptions

- .circleci/config.yml
- .lagoon.yml
- docker-compose.yml
- docs/Dockerfile
- Add Lagoon integration
- Resolves #181
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/182"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> chore(#181): add Lagoon and docker files

- .gitpod.yml
Fixes #186 by adding the missing `before` task.
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/187"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix(#186): added missing before task

- .changeset/cyan-clocks-shout.md
- .changeset/lazy-pandas-clap.md
- .changeset/popular-trainers-yell.md
- fixed #188 by adding missing changesets
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/189"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> chore(#188): add missing docgen changesets

- docs/content/guide/README.md
- docs/content/guide/client.md
- docs/content/guide/deprecations.md
- docs/content/guide/getting-started.md
- docs/content/guide/storybook.md
- docs/content/guide/theming.md
- docs/store/index.js
- Updated order of guide pages
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/196"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> chore(#175): re-order guide pages

- .changeset/strong-fans-cross.md
- packages/site/src/components/DruxtSite.vue
- packages/site/test/components/DruxtSite.test.js
- Added a fallback to the Nuxt component if no blocks are set
- Resolves #99 
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/203"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix(#99): add fallback to Nuxt component

- .changeset/spotty-chicken-breathe.md
- packages/site/src/components/DruxtSite.vue
- packages/site/test/components/DruxtSite.test.js
- Added BlockRegion $refs to the DruxtSite component
- Resolves #96
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/204"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat(#96): add BlockRegion $refs to DruxtSite

- .circleci/config.yml
- bundlewatch.config.js
- package.json
- yarn.lock
- Added Bundlewatch
- Added CircleCI job for Bundlewatch
- Resolves #205
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/206"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> chore(#205): add bundlewatch

- bundlewatch.config.js
- Updated bundlewatch config to set PR base branch
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/207"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> chore(#205): update bundlewatch config

- .changeset/clean-balloons-pump.md
- packages/router/src/nuxtModule.js
- Enabled the Nuxt Vuex store by default
- Resolves #237
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/238"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat(#237): enable Nuxt vuex store

- .changeset/famous-ads-double.md
- docs/content/modules/router/README.md
- packages/router/README.md
- packages/router/src/nuxtModule.js
- packages/router/test/nuxtModule.test.js
- Added option to disable wildcard route
- Resolves #240
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/241"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat(#240): add option to disable wildcard route

- .changeset/tall-rockets-sneeze.md
- docs/content/modules/router/README.md
- examples/nuxt/druxt-site/nuxt.config.js
- packages/router/README.md
- packages/router/src/nuxtModule.js
- packages/router/test/nuxtModule.test.js
- Added option to disable `pages/` routes
- Resolved #131
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/242"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat(#131): add option to disable `pages/`

- .circleci/config.yml
- .eslintrc.js
- .husky/pre-commit
- package.json
- packages/blocks/src/components/DruxtBlock.vue
- packages/blocks/src/components/DruxtBlockRegion.vue
- packages/blocks/src/nuxtModule.js
- packages/breadcrumb/src/components/DruxtBreadcrumb.vue
- packages/breadcrumb/src/module.js
- packages/druxt/src/components/Druxt.vue
- packages/druxt/src/components/DruxtModule.vue
- packages/entity/src/components/DruxtEntity.vue
- packages/entity/src/components/DruxtEntityForm.vue
- packages/entity/src/components/DruxtField.vue
- packages/entity/src/components/fields/DruxtFieldEntityReferenceLabel.vue
- packages/entity/src/components/fields/DruxtFieldFileDefault.vue
- packages/entity/src/components/fields/DruxtFieldImage.vue
- packages/entity/src/components/fields/DruxtFieldResponsiveImage.vue
- packages/entity/src/mixins/componentSuggestion.js
- packages/entity/src/nuxtModule.js
- packages/menu/src/nuxtModule.js
- packages/router/src/components/DruxtRouter.vue
- packages/router/src/nuxtModule.js
- packages/router/src/stores/router.js
- packages/schema/src/nuxtModule.js
- packages/site/src/nuxtModule.js
- packages/views/src/components/DruxtView.vue
- packages/views/src/components/blocks/DruxtBlockViewsBlock.vue
- packages/views/src/nuxtModule.js
- yarn.lock
- Fixed ESLint
- Added husky pre-commit hook
- Fixed linting issues
- Resolved #244
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/245"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> chore(#244): fix eslint

- .changeset/odd-clouds-deliver.md
- packages/blocks/nuxt/druxt-block-region.stories.js
- packages/blocks/nuxt/druxt-block.stories.js
- packages/entity/nuxt/druxt-entity-form.stories.js
- packages/entity/nuxt/druxt-entity.stories.js
- packages/menu/nuxt/druxt-menu.stories.js
- packages/views/nuxt/druxt-views.stories.js
- Updated path to components
- Resolved #250
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/251"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix(#250): update path to components

- .changeset/slimy-games-behave.md
- .changeset/unlucky-socks-hug.md
- packages/blocks/src/components/DruxtBlock.vue
- packages/blocks/test/components/DruxtBlock.test.js
- packages/druxt/src/components/DruxtDebug.vue
- packages/druxt/src/components/DruxtModule.vue
- packages/druxt/test/components/DruxtModule.test.js
- packages/entity/src/components/DruxtEntity.vue
- packages/entity/src/components/DruxtField.vue
- packages/entity/test/components/DruxtEntity.test.js
- packages/entity/test/components/__snapshots__/DruxtEntity.test.js.snap
- Added DruxtDebug component
- Updated modules to use DruxtDebug component
- Resolved #253
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/254"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat(#253): add DruxtDebug component

- .changeset/smooth-squids-rule.md
- packages/druxt/package.json
- packages/druxt/src/nuxtModule.js
- packages/druxt/test/nuxtModule.test.js
- yarn.lock
- Added Druxt API URL to Nuxt CLI badge
- Resolved #255 
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/257"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat(#255): add Druxt API url to Nuxt badge

- packages/druxt/README.md
- Added missing README to the Druxt package
- Resolved #256
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/258"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> chore(#256): add druxt package README

- packages/blocks/README.md
- packages/breadcrumb/README.md
- packages/entity/README.md
- packages/menu/README.md
- packages/router/README.md
- packages/schema/README.md
- packages/site/README.md
- packages/views/README.md
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/271"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> chore(#269): update package readme files

- .changeset/mean-birds-shop.md
- .gitignore
- CONTRIBUTING.md
- docs/content/.gitignore
- packages/docgen/src/index.js
- Added CONTRIBUTING.md
- Added Docgen task to copy file to documentation website
- Resolved #148
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/272"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> chore(#148): add CONTRIBUTING.md

- .circleci/config.yml
- package.json
- renovate.json
- yarn.lock
- Updated renovate config to group eslint and jest
- Added renovate config validator
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/274"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> chore(#211): update renovate config

- .changeset/tricky-carrots-jam.md
- packages/druxt/src/client.js
- Fixed issue with Axios settings being removed
- Resolved #263
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/264"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix(#263): don't delete axios settings

- packages/blocks/package.json
- packages/blocks/src/nuxtModule.js
- packages/breadcrumb/package.json
- packages/breadcrumb/src/nuxtModule.js
- packages/druxt/package.json
- packages/entity/package.json
- packages/menu/package.json
- packages/menu/src/nuxtModule.js
- packages/router/package.json
- packages/router/src/nuxtModule.js
- packages/schema/package.json
- packages/site/package.json
- packages/views/package.json
- packages/views/src/nuxtModule.js
- yarn.lock
- Updated packages metadata
- Updated nuxt modules metadata
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/291"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> chore: update packages metadata

- .changeset/heavy-peaches-kneel.md
- packages/breadcrumb/src/components/DruxtBreadcrumb.vue
- Ensure crumbs is array if empty
- Resolved #295 
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/296"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix(#295): ensure crumbs is an array if empty

- .changeset/sour-parrots-agree.md
- packages/views/package.json
- Added `templates` to the package manifest
- Resolves #300
> fix(#300): add templates

- .changeset/witty-flowers-help.md
- packages/views/src/components/DruxtView.vue
- packages/views/test/components/DruxtView.test.js
- Added arguments prop to DruxtView component
- Resolves #304 
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/306"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat: add support for Contextual filters

- .changeset/mighty-kiwis-accept.md
- packages/blocks/src/components/DruxtBlock.vue
- packages/blocks/src/components/DruxtBlockRegion.vue
- packages/breadcrumb/src/components/DruxtBreadcrumb.vue
- packages/druxt/src/components/DruxtModule.vue
- packages/druxt/test/components/DruxtModule.test.js
- packages/entity/src/components/DruxtEntity.vue
- packages/entity/test/components/DruxtEntity.test.js
- packages/menu/src/components/DruxtMenu.vue
- packages/menu/test/components/DruxtMenu.test.js
- packages/site/src/components/DruxtSite.vue
- packages/views/src/components/DruxtView.vue
- packages/views/test/components/DruxtView.test.js
- test/__fixtures__/get/011a7a912fd70f4ec24f0d3e98ea1d4e.json
- test/__fixtures__/get/7fa7f0fb60ec3cad8310ed0c27f008e8.json
- test/__fixtures__/get/8d22be955924857b99097ac24330eccb.json
- Refactored the DruxtModule:
- Added fetchConfig hook; Fetch any config required to determine the Wrapper component
- Added settings hook; Merge settings from the Wrapper component, global settings and instance properties
- Added fetchData hook; Fetch main component data using merged settings
- Updated modules to use new hooks.
- Resolved #352 
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/353"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> refactor(#352): add druxt fetch and settings hooks

- .changeset/kind-paws-hide.md
- packages/views/src/components/DruxtViewsFilter.vue
- Fixed missing default values in DruxtViewsFilter template
- Resolves #365
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/366"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix(#365): add wrapper default values

- .changeset/brave-walls-change.md
- .changeset/brown-peaches-camp.md
- docs/content/modules/entity/README.md
- examples/nuxt/entity-queries/README.md
- examples/nuxt/entity-queries/components/druxt/entity/node/Article.vue
- examples/nuxt/entity-queries/components/druxt/entity/node/Recipe.vue
- examples/nuxt/entity-queries/components/druxt/entity/node/RecipeTeaser.vue
- examples/nuxt/entity-queries/nuxt.config.js
- examples/nuxt/entity-queries/package.json
- examples/nuxt/entity-queries/pages/index.vue
- packages/entity/src/components/DruxtEntity.vue
- packages/entity/test/components/DruxtEntity.test.js
- packages/entity/test/components/DruxtField.test.js
- packages/entity/test/components/__snapshots__/DruxtEntity.test.js.snap
- packages/entity/test/components/__snapshots__/DruxtField.test.js.snap
- packages/entity/test/components/fields/__snapshots__/DruxtFieldEntityReferenceEntityView.test.js.snap
- test/__fixtures__/get/068643cd809f67ffcc5600431759a3cf.json
- test/__fixtures__/get/0dd04a1e4b089da254bfceb74fe40daa.json
- test/__fixtures__/get/1c8dcfa3f105262d7e287b37ebc6e190.json
- test/__fixtures__/get/232312fabda85a9f7f331cb6b6d89f5a.json
- test/__fixtures__/get/2ca68a5ffb40da0629c1bd8b06792303.json
- test/__fixtures__/get/346bceb7746b0569e4719ac5cb2641c1.json
- test/__fixtures__/get/591df8bd9b9f814fd09c7661fa2d8c55.json
- test/__fixtures__/get/8b7b4f16af0cb8801af7be0ab41177d3.json
- test/__fixtures__/get/befd7cdc622e1d1a5986311dc8029808.json
- test/__fixtures__/get/d23e4364dc304e368f26d9e53e23db58.json
- test/__fixtures__/get/d95cabaca80e163924f2c126dd32a358.json
- test/__fixtures__/patch/232312fabda85a9f7f331cb6b6d89f5a/c988a9ec0ef7d5843026d0d684e63ade.json
- Added **include** to query settings to include related resources
- Added option to filter included **fields**
```js
export default {
druxt: {
query: {
include: ['field_media_image', 'field_media_image.field_media_image'],
fields: [['file--file', ['uri']], ['media--image', []]],
}
}
}
```
- Added a **settings** property to the DruxtEntity component allowing settings to be set at the module component level.
```jsx
<template>
<DruxtEntity v-bind="props" :settings="{ query: { include:['uid'] } }" />
</template>
```
Resolves #355 
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/361"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat(#355): add query settings to allow including related resources

- .changeset/ninety-olives-allow.md
- packages/entity/src/components/DruxtEntity.vue
- Fixed Vuex mutation in DruxtEntity fetch hook.
- Resolves #370 
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/374"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix(#370): clone resource data before mutating

- .changeset/dry-mayflies-live.md
- .changeset/itchy-donuts-notice.md
- .changeset/perfect-rings-push.md
- .changeset/purple-queens-cry.md
- docs/content/modules/router/README.md
- examples/nuxt/druxt-site/nuxt.config.js
- examples/nuxt/router-modes/README.md
- examples/nuxt/router-modes/nuxt.config.js
- examples/nuxt/router-modes/package.json
- examples/nuxt/router-modes/pages/en/recipes/_slug.vue
- examples/nuxt/router-modes/pages/index.vue
- packages/router/src/components/DruxtRouter.stories.js
- packages/router/src/components/DruxtRouter.vue
- packages/router/src/mixins/router.js
- packages/router/src/nuxt/index.js
- packages/router/test/components/DruxtRouter.test.js
- packages/router/test/nuxt/index.test.js
- Added fetch hook to DruxtRouter component; This allows the component to be used inside of a Vue page or component.
- Added path prop to DruxtRouter component; Allows rendering of a specified route, defaults to Vue router full path.
- Added storybook integration/story for DruxtRouter component.
- Added option to disable middleware; allows you to prevent any queries from the router to the backend, allowing for serverless static builds.
- Resolves #376
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/377"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat(#376): improve ability to use DruxtRouter component

- .changeset/fast-dolphins-act.md
- examples/nuxt/debug-component/README.md
- examples/nuxt/debug-component/nuxt.config.js
- examples/nuxt/debug-component/package.json
- examples/nuxt/debug-component/pages/index.vue
- packages/druxt/src/components/DruxtDebug.vue
- Add JSON prop to DruxtDebug component to provide formatted JSON data
```jsx
<DruxtDebug :json="{ entity: { attributes: {} } }" />
- Resolves #383
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/386"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat(#383): add ability to debug JSON data

- .changeset/wicked-moles-hunt.md
- packages/druxt/src/nuxtModule.js
- Added Druxt version to badge.
- Resolves #373
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/389"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat(#373): add druxt version to nuxt badge

- .changeset/kind-tools-marry.md
- packages/views/src/components/DruxtViewsFilter.vue
- Removes the custom render template and watch method from the DruxtViewsFilter; This allows it to use the common DruxtModule render method which has fixes for various issues, including hydration leaks.
- This does result in some changes to the rendered markup, would could potentially break an implementation.
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/402"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix(#397): remove custom template

- .changeset/flat-laws-beg.md
- packages/druxt/src/components/DruxtModule.vue
- Removes the DruxtModule fetchstate check once the theme component is known to reduce fetch state based UI flickering.
- Resolves #397 
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/403"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix(#397): reduce fetchstate pending flicker

- packages/druxt/src/client.js
- packages/druxt/src/components/DruxtModule.vue
- packages/druxt/src/stores/druxt.js
- packages/druxt/test/__snapshots__/client.test.js.snap
- packages/druxt/test/client.test.js
- packages/druxt/test/components/DruxtModule.test.js
- packages/druxt/test/components/__snapshots__/DruxtModule.test.js.snap
- Fixes an issue introduced in #408
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/411"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix(#408): add more context to error message

- .changeset/big-mice-train.md
- .changeset/loud-years-work.md
- packages/entity/src/components/DruxtEntity.vue
- packages/entity/src/components/DruxtRouterEntity.vue
- packages/schema/templates/plugin.js
- Updated DruxtRouterEntity to use Full view mode to render entities.
- Add fallback to Default if schema view mode is missing.
- Resolves #412
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/414"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat(#412): update Entity router to use full mode

- .changeset/ten-apricots-visit.md
- packages/entity/src/components/DruxtEntity.vue
- packages/entity/test/components/DruxtEntity.test.js
- packages/entity/test/components/__snapshots__/DruxtEntity.test.js.snap
- Added DruxtEntity[EntityType][ViewMode][SchemaType] component options.
- Resolved #417
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/418"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat(#417): add more component options

- .changeset/slow-singers-act.md
- packages/blocks/src/index.js
- packages/blocks/src/mixins/block.js
- packages/blocks/src/mixins/index.js
- packages/blocks/src/mixins/region.js
- Added DruxtBlocksRegionMixin mixin for DruxtBlockRegion wrapper components.
- Resolved #112 
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/428"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat(#112): add DruxtBlocksRegionMixin

- .changeset/fast-bottles-yell.md
- .changeset/spotty-colts-attack.md
- packages/blocks/src/components/DruxtBlockRegion.vue
- packages/blocks/test/components/DruxtBlockRegion.test.js
- Added watch/fetch for theme and name to DruxtBlockRegion
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/432"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat(#429): add watch fetch for DruxtBlockRegion

- .gitpod.yml
- .gitpod/scripts/ddev-setup.sh
- .gitpod/scripts/drupal-setup.sh
- examples/drupal/drupal-9/.ddev/commands/web/drupal-install
- examples/drupal/drupal-9/.ddev/config.yaml
- examples/drupal/drupal-9/README.md
- examples/drupal/drupal-9/composer.json
- Update ddev to 1.18.2
- Resolves #420
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/431"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> chore(#420): update ddev to 1.18.2

- .changeset/tiny-bees-crash.md
- packages/breadcrumb/src/components/DruxtBreadcrumb.vue
- packages/breadcrumb/test/components/DruxtBreadcrumb.test.js
- packages/breadcrumb/test/components/__snapshots__/DruxtBreadcrumb.test.js.snap
- Added the `path` prop to the DruxtBreacrumb.
- Resolves #433
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/434"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat(#433): add path prop to DruxtBreadcrumb

- .changeset/wet-foxes-wash.md
- packages/breadcrumb/src/components/DruxtBreadcrumb.vue
- packages/breadcrumb/test/components/DruxtBreadcrumb.test.js
- Added watch/fetch from `home` and `path` props.
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/435"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat(#429): add watch/fetch for DruxtBreadcrumb

- .babelrc
- .circleci/config.yml
- jest.config.js
- package.json
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/452"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> chore(#443): update jest config

- .changeset/stupid-drinks-breathe.md
- README.md
- packages/druxt/package.json
- packages/druxt/src/client.js
- packages/druxt/src/nuxt/index.js
- packages/druxt/templates/plugin.js
- packages/druxt/test/client.test.js
- packages/druxt/test/nuxt/index.test.js
- packages/druxt/test/stores/druxt.test.js
- packages/router/test/components/DruxtRouter.test.js
- packages/router/test/router.test.js
- packages/router/test/stores/router.test.js
- packages/schema/test/schema.test.js
- packages/schema/test/utils/schema.test.js
- packages/views/test/stores/views.test.js
- yarn.lock
- Added support for the @nuxtjs/axios module
- Resolves #63
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/406"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat(#63): add support for @nuxtjs/axios

- .changeset/old-steaks-arrive.md
- examples/nuxt/druxt-site/nuxt.config.js
- packages/menu/src/components/DruxtMenuItem.vue
- packages/menu/test/components/DruxtMenuItem.test.js
- packages/menu/test/components/__snapshots__/DruxtMenuItem.test.js.snap
- Adds handling for External links in the DruxtMenuItem component.
- Resolved #103
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/463"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix(#103): add better support for external links

- .changeset/selfish-birds-fry.md
- packages/druxt/src/nuxt/index.js
- Updated Axios proxy to be enabled when the API proxy is enabled.
- Resolved #465
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/466"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix(#465): update axios proxy logic

- .circleci/config.yml
- package.json
- packages/entity/test/components/fields/Deprecations.test.js
- yarn.lock
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/470"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> chore(#211): update siroc and esbuild

- docs/content/guide/storybook.md
- Update install steps for Storybook
- resolves #437 
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/475"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> chore(#437): update storybook install

- .changeset/stale-rice-cheer.md
- packages/views/src/components/DruxtView.vue
- packages/views/test/components/DruxtView.test.js
- packages/views/test/components/__snapshots__/DruxtView.test.js.snap
- Added more available options
- Resolved #485 
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/487"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat(#485): fix available component options

- examples/drupal/drupal-9/.ddev/docker-compose.network-mtu.yaml
- Added DDev / Drupal.org MTU network issue fix provided by @shaal
- Resolves #489
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/490"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix(#489): add ddev mtu fix

- .gitpod/Dockerfile
- Removed composer hash check
- Resolves #495
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/496"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix(#495): removed composer check

- .changeset/funny-guests-complain.md
- packages/druxt/src/nuxt/index.js
- packages/router/src/nuxt/index.js
- Check if site has languages configured before trying to full data from them.
- Resolved #508 
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/509"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix(#508): fix error on single lingual sites

- .changeset/twelve-squids-marry.md
- packages/router/src/nuxt/index.js
- Add filter to lang `((o) => o)`
- Fixed #513 
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/514"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix(#513): add filter to languages

- .changeset/empty-eels-float.md
- packages/druxt/src/nuxt/index.js
- packages/router/src/nuxt/index.js
- Fixed single lingual and JSON:API Extras bug by adding additional conditional
- Resolved #515
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/516"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix(#515): fix json:api extras single lingual bug

- .changeset/smooth-kids-reflect.md
- packages/views/src/components/DruxtView.vue
- Prevents error if `model.filter` is undefined.
- Fixes #520
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/521"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix(#520): add fix for undefined errors

- .changeset/eleven-buckets-tickle.md
- packages/entity/src/nuxtStorybook.js
- Added status filter to DruxtEntity Storybook collection query.
- Fixed #522
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/523"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix(#522): add status filter to collection query

- .changeset/brown-moose-mix.md
- packages/druxt/src/nuxt/index.js
- Normalize slashes on baseUrl and endpoint
- Resolves #525
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/528"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat(#525): normalize slashes

- .changeset/long-spoons-smile.md
- packages/blocks/templates/druxt-block.stories.js
- packages/breadcrumb/templates/druxt-breadcrumb.stories.js
- packages/entity/templates/druxt-entity.stories.js
- packages/menu/templates/druxt-menu.stories.js
- packages/router/templates/druxt-router.stories.js
- packages/site/templates/druxt-site.stories.js
- packages/views/templates/druxt-views.stories.js
- Adds **extends** props to module component stories
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/534"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> chore(#501): add extends props to storybook

- .changeset/itchy-roses-cross.md
- .changeset/lazy-wasps-deliver.md
- .changeset/pink-laws-boil.md
- .changeset/ten-vans-drum.md
- .changeset/three-emus-deny.md
- .changeset/tidy-melons-add.md
- packages/breadcrumb/src/nuxtModule.js
- packages/menu/src/nuxtModule.js
- packages/menu/test/nuxtModule.test.js
- packages/router/src/nuxt/index.js
- packages/router/test/nuxt/index.test.js
- Enabled Nuxt module dependencies for:
- druxt-breadcrumb
- druxt-menu
- druxt-router
- Resolves #349 
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/540"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat(#349): enable dependencies

- .changeset/thin-toes-design.md
- .changeset/wicked-maps-change.md
- packages/druxt/src/client.js
- packages/schema/src/schema.js
- packages/schema/test/schema.test.js
- Removed the permission check from the DruxtClient get request.
- Add permission check to the DruxtSchema module.
- Resolves #543
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/548"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix(#543): updated permission checks

- docs/drupal/composer.json
- docs/drupal/composer.lock
- docs/drupal/config/sync/core.entity_view_display.media.image.medium_8_7.yml
- docs/drupal/config/sync/core.entity_view_display.media.image.scale_crop_7_3_large.yml
- docs/drupal/config/sync/core.entity_view_display.user.user.compact.yml
- docs/drupal/config/sync/core.entity_view_display.user.user.default.yml
- docs/drupal/config/sync/core.extension.yml
- docs/drupal/config/sync/jsonapi.settings.yml
- docs/drupal/config/sync/language.types.yml
- docs/drupal/config/sync/views.view.media.yml
- docs/drupal/config/sync/views.view.media_library.yml
- docs/drupal/web/.htaccess
- docs/drupal/web/sites/default/default.settings.php
- Updated Drupal to 9.4
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/558"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> chore(examples): update drupal to 9.4

- .circleci/config.yml
- docs/nuxt/package.json
- docs/nuxt/pages/index.vue
- docs/nuxt/test/cypress.config.js
- docs/nuxt/test/cypress/e2e/api-docs.cy.js
- docs/nuxt/test/cypress/e2e/get-started.cy.js
- docs/nuxt/test/cypress/e2e/homepage.cy.js
- docs/nuxt/test/cypress/e2e/modules.cy.js
- docs/nuxt/test/cypress/e2e/search.cy.js
- docs/nuxt/test/cypress/support/commands.js
- docs/nuxt/test/cypress/support/e2e.js
- docs/nuxt/yarn.lock
- renovate.json
- Adds Cypress tests to the DruxtJS.org documentation site
- Resolved #562 
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/564"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> chore(#562): add cypress tests to docs site

- .changeset/big-worms-punch.md
- packages/entity/src/components/DruxtField.vue
- packages/entity/test/components/__snapshots__/DruxtField.test.js.snap
Adds passthrough attrs from DruxtField to DruxtEntity components.
> fix(#632): add passthrough attrs to DruxtField

- docs/nuxt/Dockerfile
- docs/nuxt/package.json
- docs/nuxt/yarn.lock
- update amazee node images
- workaround for deasync issue
> chore(#641): workaround for deasync

- .changeset/angry-panthers-prove.md
- .changeset/few-pets-suffer.md
- .changeset/khaki-glasses-sing.md
- packages/druxt/src/stores/druxt.js
- packages/druxt/test/stores/druxt.test.js
- packages/entity/src/components/DruxtEntity.vue
- packages/views/src/components/DruxtView.vue
- packages/views/src/stores/views.js
- packages/views/test/stores/views.test.js
- Druxt
- added druxt/flushCollection and druxt/flushResource mutations
- added bypassCache option to druxt/getCollection and druxt/getResource actions
- Druxt Views
- added druxt/views/flushResults mutation
- added bypassCache option to druxt/views/getResults action
- added druxt.query.bypassCache option to DruxtView
> feat(#639): add cache control to druxt views

- packages/views/src/components/DruxtView.vue
> chore(#639): cleanup console.log

- .changeset/eleven-moons-sort.md
- packages/blocks/package.json
- packages/views/package.json
- yarn.lock
> fix: resolve axios dependency issue

- .changeset/small-jeans-smell.md
- packages/druxt/src/components/DruxtWrapper.vue
- packages/entity/test/components/__snapshots__/DruxtField.test.js.snap
- Add Attrs passthrough to the DruxtWrapper component.
> feat(#87): add attrs passthrough to DruxtWrapper component
