druxt/druxt.js

- .gitpod.yml
This PR updates `.gitpod.yml` to run prebuilds automatically for every branch, fork, etc.
The missing step is configuring Gitpod Bot to have access to the repo, follow these instructions - https://github.com/apps/gitpod-io
> Adding Gitpod's prebuild automation rules

- examples/nuxt/druxt-site/package.json
Swaps `nuxt-edge` for `nuxt`, as the latest `-edge` seems to be missing from the npm registry(?)
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/146"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
Fixed #145
> fix(#145): change `nuxt-edge` to `nuxt`

- .changeset/modern-tigers-press.md
- .changeset/old-parrots-shave.md
- docs/content/modules/site/README.md
- examples/nuxt/druxt-site/layouts/default.vue
- examples/nuxt/druxt-site/nuxt.config.js
- packages/site/package.json
- packages/site/src/components/DruxtSite.vue
- packages/site/src/layouts/default.vue
- packages/site/src/nuxtModule.js
- packages/site/test/components/DruxtSite.test.js
- packages/site/test/nuxtModule.test.js
- test/__fixtures__/get/7a748bd9d861469c22ca962ae6f783b0.json
- Adds a default layout and option, on by default if there's no layouts in the codebase: `druxt.site.layout`
- Adds default theme option and fallback for the DruxtSite component: `druxt.site.theme`
- Updates the Site module settings for better module level settings.
- Resolves #285 
- Resolves #98 
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/286"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat: add default Site layout and theme settings

- .changeset/afraid-coins-smash.md
- .changeset/clever-shrimps-vanish.md
- .gitignore
- docs/content/modules/router/README.md
- package.json
- packages/router/README.md
- packages/router/package.json
- packages/router/src/index.js
- packages/router/src/nuxt/index.js
- packages/router/test/nuxt/index.test.js
- packages/site/src/nuxtModule.js
- Moved Nuxt module to `druxt-router/nuxt`
- Added check for `pages/` directory
- Resolves #292 
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/294"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat(#292): set `pages` default based on `pages/` directory

- .changeset/forty-sheep-retire.md
- packages/views/src/components/DruxtView.vue
- Added conditional defaults to prevent errors when no props provided to DruxtView component
- Fixed #297
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/298"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix(#297): add conditional defaults to stop errors

- .changeset/sweet-numbers-help.md
- examples/nuxt/druxt-site/nuxt.config.js
- packages/druxt/src/nuxtModule.js
- packages/druxt/test/nuxtModule.test.js
- packages/site/src/nuxtModule.js
- packages/site/test/nuxtModule.test.js
- Enabled Nuxt components auto-discovery option by default.
- Resolves #310
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/316"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat(#310): add default for nuxt components option

- .changeset/twenty-fireants-collect.md
- docs/content/guide/theming.md
- examples/nuxt/wrappers/README.md
- examples/nuxt/wrappers/components/druxt/entity/node/Page.vue
- examples/nuxt/wrappers/nuxt.config.js
- examples/nuxt/wrappers/package.json
- examples/nuxt/wrappers/pages/index.vue
- packages/druxt/src/components/DruxtModule.vue
- packages/druxt/test/components/DruxtModule.test.js
- Changed template injected components to be unwrapped by default
- Resolves #312
Example:
```jsx
<template>
<DruxtEntity v-bind="props">
<template #default="{ entity }">
// This would no longer be wrapped by DruxtEntityNode[Type], etc.
</template>
</DruxtyEntity>
</template>
```
This is a change to the current default behaviour, as a template injected component is currently wrapped. However in my usage I've found that this is not the desired default behaviour.
It's still possible to wrap a template injected component by setting a value to the `wrapper` property, either the standard Object values or `true`
Example:
```jsx
<template>
<DruxtEntity v-bind="props" :wrapper="true">
<template #default="{ entity }">
// This would be wrapped by DruxtEntityNode[Type], etc.
</template> …
```
> feat(#312): unwrap template injected components

- .changeset/unlucky-papayas-pull.md
- packages/druxt/src/components/DruxtDebug.vue
- Makes summary field optional, and defaults to "Debug".
- Resolves #384
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/385"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat(#384): make summary prop optional

- .changeset/strange-ears-peel.md
- packages/druxt/package.json
- packages/druxt/src/client.js
- packages/druxt/test/client.test.js
- yarn.lock
- Added `debug` mode
- Added Axios request logging when debug mode enabled.
- Resolves #69
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/388"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat(#69): add debug mode and axios logging

- .changeset/funny-weeks-greet.md
- packages/druxt/src/index.js
- packages/druxt/src/nuxt/index.js
- packages/druxt/test/nuxt/index.test.js
- Moved the Nuxt module to the `src/nuxt` directory
- Added extendPlugins to make the $druxt plugin the first loaded
- Resolves #357
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/404"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat(#357): make $druxt plugin first

- .changeset/slow-keys-provide.md
- packages/blocks/src/components/DruxtBlock.vue
- packages/druxt/src/components/DruxtModule.vue
- packages/entity/src/components/DruxtEntity.vue
- packages/entity/templates/druxt-entity-form.stories.js
- packages/entity/templates/druxt-entity.stories.js
- packages/views/templates/druxt-views.stories.js
- Fixed various minor errors in storybook.
- Resolves #419 
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/421"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix(#419): Fix errors in storybook

- .changeset/fast-bottles-yell.md
- packages/blocks/src/components/DruxtBlock.vue
- packages/blocks/test/components/DruxtBlock.test.js
- Adds a watch for ID and UUID to the DruxtBlock component; This allows reactive storybook integration.
- Resolves #429
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/430"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat(#429): add id and uuid watch

- .changeset/wild-humans-cough.md
- packages/entity/templates/druxt-entity-form.instance.stories.js
- packages/entity/templates/druxt-entity.instance.stories.js
- Escapes Entity and Entity form titles for UUID in Storybook.
- Resolves #438
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/439"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix(#438): add escaping to story title

- .changeset/wicked-tables-tie.md
- packages/blocks/package.json
- packages/druxt/package.json
- packages/entity/package.json
- packages/menu/package.json
- packages/schema/package.json
- packages/site/package.json
- packages/test-utils/package.json
- packages/views/package.json
Beep boop! fake renovate bot here!
Updated drupal-json-api params to version 2.0.0.
The version bump to 2.x is due to a bug fix surrounding "shortening" of generated url. It doesn't change the behaviour of response from Drupal, but might break some tests if you have any.
I tried to setup druxt.js in local for running test, however am facing some roadblocks, hence didn't run test to check if there had been any breaking change. 
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/481"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> chore: update drupal-jsonapi-params to ^2.0.0

- .changeset/sweet-pumpkins-behave.md
- packages/druxt/src/client.js
- Fix API proxy when using deprecated Axios options method.
- resolves #497 
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/498"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix(#497): add proxy settings for deprecated axios

- .changeset/smart-bags-share.md
- packages/druxt/src/nuxt/index.js
- packages/druxt/test/nuxt/index.test.js
- Changed the order of Druxt Proxy entries, allowing users to override proxy entries.
- Fixed #518 
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/519"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix(#518): change order of druxt proxies

- .changeset/itchy-roses-cross.md
- .changeset/three-emus-deny.md
- .changeset/tidy-melons-add.md
- packages/entity/src/components/DruxtEntity.vue
- packages/site/src/components/DruxtSite.vue
- packages/views/src/components/DruxtView.vue
- packages/views/test/components/DruxtView.test.js
- Added prop watches to:
- DruxtEntity: `settings`
- DruxtView: `arguments`
- DruxtSite: `theme`
- Resolves #429 
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/536"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat(#429): update module prop watches

- .changeset/real-weeks-pull.md
- packages/breadcrumb/src/components/DruxtBreadcrumb.vue
- packages/breadcrumb/test/components/DruxtBreadcrumb.test.js
- Fixed DruxtBreadcrumb component to prevent duplicate Home crumbs being created.
- Resolved #538
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/549"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix(#538): fix breadcrumb multilingual home bug

- .changeset/bright-sloths-cheat.md
- packages/menu/src/nuxtModule.js
- packages/menu/test/nuxtModule.test.js
- packages/site/src/nuxtModule.js
- Updated DruxtMenu to use JSON:API Menu Items module data by default.
- Resolved #539
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/550"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat(#539): default to JSON:API Menu Items data

- .changeset/cuddly-ears-breathe.md
- examples/druxt-site/components/druxt/field/undefined/Form.vue
- examples/druxt-site/pages/_langcode/contact.vue
- packages/entity/src/components/DruxtEntity.vue
- packages/entity/src/components/DruxtField.vue
- Sanitised empty emitted string in hijacked model watch in the DruxtField component to prevent value being replaced with `true`
- Remove empty emitted attributes and relationships from DruxtEntity model
- Resolves #552
<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/556"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix(#552): sanitise empty emitted strings

- .changeset/eighty-bikes-float.md
- packages/druxt/src/stores/druxt.js
Re-fetching resources from the `include` section in the `queryObject`
Resolves #628
> fix(#628): add prefix to included resources fetch

- .changeset/weak-years-jump.md
- packages/router/templates/plugin.js
Added support for Nuxt Axios module in Router plugin as per the same feature in the core Druxt plugin.
Fixes #660
> feat(#660): add @nuxtjs/axios support to router
